# Resolução de 10 execícios do pacote numpy 

## Verificação versão e congiguração do numpy e importação de seu nome como 'np'

Importação como do pacote numpy como np

In [1]:
import numpy as np

Verificação de versão

In [2]:
print(np.__version__)
np.show_config()

1.20.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/eder/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/eder/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/eder/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/eder/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/eder/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/eder/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/eder/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/eder/anaconda3\\Library\\include']


## Definição de vetor nulo de tamanho n

In [163]:
n=6
M_zeros = np.zeros(n)
print(M_zeros)

[0. 0. 0. 0. 0. 0.]


## Criação de matriz identidade 2x2

In [4]:
M_identidade=np.eye(2)
print(M_identidade)

[[1. 0.]
 [0. 1.]]


## Criando matriz 3x3 com valores aleatórios de 1 a 10

In [147]:
M_1_a_10 = np.random.randint(1,11,9).reshape(3,3)
print(M_1_a_10)

[[6 9 9]
 [8 4 8]
 [7 9 9]]


## Transpor matrizes

In [148]:
M_t=M_1_a_10.T
print(M_t)

[[6 8 7]
 [9 4 9]
 [9 8 9]]


## Inverter matrizes

In [150]:
M_inv=np.linalg.inv(M_1_a_10)
print(M_inv)

[[-1.00000000e+00 -2.77555756e-17  1.00000000e+00]
 [-4.44444444e-01 -2.50000000e-01  6.66666667e-01]
 [ 1.22222222e+00  2.50000000e-01 -1.33333333e+00]]


## Produto matricial

In [151]:
M_produto_identidade = np.dot(M_1_a_10,M_inv)
print(np.around(M_produto_identidade))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Resolução de sistema de equação linear 3x3

Sistema de equação:
- (1):   6x1 + 9x2 + 9x3  = 1
- (2):   8x1 + 4x2 + 8x3  = 2
- (3):   7x1 + 9x2 + 9x3 = 3

Utilizando o método das matrizes, temos:

In [160]:
B=np.arange(1,4)
print("matriz dos termos constantes",'\n',B)
print("matriz dos coeficientes","\n",M_1_a_10)
X = np.dot(M_inv,B)
print("matrizes das incógnitas","\n",X)

matriz dos termos constantes 
 [1 2 3]
matriz dos coeficientes 
 [[6 9 9]
 [8 4 8]
 [7 9 9]]
matrizes das incógnitas 
 [ 2.          1.05555556 -2.27777778]


## Acumular elementos de diferentes elemento de vetores

In [203]:
Arr_acumulado =  np.concatenate((X, M_zeros,B))
print("Matriz acumuladas \n",Arr_acumulado)

Matriz acumuladas 
 [ 2.          1.05555556 -2.27777778  0.          0.          0.
  0.          0.          0.          1.          2.          3.        ]


## Verificação de frequência exclusiva de elementos em um Vetor

In [207]:
Fre_Arr_acumulado= np.unique(Arr_acumulado, return_counts=True)
print(Fre_Arr_acumulado)


(array([-2.27777778,  0.        ,  1.        ,  1.05555556,  2.        ,
        2.        ,  3.        ]), array([1, 6, 1, 1, 1, 1, 1], dtype=int64))
